version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pawshop_app
    restart: unless-stopped
    tty: true
    env_file:
      - .docker.env
    volumes:
      - ./:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  nginx:
    image: nginx:1.17
    container_name: pawshop_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  mysql:
    image: mysql:5.7.27
    container_name: pawshop_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    container_name: pawshop_phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysql
